apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: omnicraft
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - omnicraft.example.com
      secretName: omnicraft-tls
  rules:
    - host: omnicraft.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: omnicraft
                port:
                  name: http
