apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omnicraft

resources:
  - ../../base
  - route.yaml

patches:
  - path: deployment-patch.yaml
  - target:
      kind: Ingress
      name: omnicraft
    patch: |
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: omnicraft
