apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: omnicraft
  labels:
    app: omnicraft
spec:
  host: omnicraft.apps.example.com
  to:
    kind: Service
    name: omnicraft
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
